// UI Components exports
export { default as Button } from './Button'
export { default as Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from './Card'
export { default as Input } from './Input'
export { default as Modal, ModalHeader, ModalTitle, ModalDescription, ModalBody, ModalFooter } from './Modal'
export { default as Badge, StatusBadge } from './Badge'
export { default as EmptyState } from './EmptyState'
export { default as LoadingSpinner, LoadingOverlay } from './LoadingSpinner'
export { default as StatCard } from './StatCard'
export { default as Table, TableHeader, TableBody, TableRow, TableHead, TableCell, EmptyTable } from './Table'
export { default as Chart } from './Chart'
export { default as Heatmap } from './Heatmap'
export { default as StudentPerformanceChart } from './StudentPerformanceChart'

// Re-export types
export type { ButtonProps } from './Button'
export type { CardProps, CardHeaderProps, CardTitleProps, CardDescriptionProps, CardContentProps, CardFooterProps } from './Card'
export type { InputProps } from './Input'
export type { ModalProps, ModalHeaderProps, ModalTitleProps, ModalDescriptionProps, ModalBodyProps, ModalFooterProps } from './Modal'
export type { BadgeProps, StatusBadgeProps } from './Badge'
export type { EmptyStateProps } from './EmptyState'
export type { LoadingSpinnerProps, LoadingOverlayProps } from './LoadingSpinner'
export type { StatCardProps } from './StatCard'
export type { TableProps, TableHeaderProps, TableBodyProps, TableRowProps, TableHeadProps, TableCellProps, EmptyTableProps } from './Table'
